logging:
  config: classpath:logback-spring.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/training?nullNamePatternMatchesAll=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  profiles:
    active: dev
app-config:
  config:
    amount-thread: 4
    step: 1000
    limit-start: 0
    batch-size: 10000
  models:
    - table: patient_info
      id-name: id_patient_info
      fields: [First_Name, Last_Name, Phone, City, State, ZIP, Address, Gender, DOB]
    - table: physician_info
      id-name: id_physician_info
      fields: [First_Name, Last_Name, Phone, City, State, ZIP, Address, NPI]
    - table: insurance_info
      id-name: id_insurance_info
      fields: [Policy, Group_field]